"""The axiom-battery: scientific_invention_axioms.md §9, run on this substrate.

The source document (P-4/P-5) demands leakage-controlled origination probes:
present the MECHANISM of an eponymous law under neutral vocabulary and ask
whether the system recovers its structure — the law itself never named in the
input. These tests do exactly that at the level CANDOR operates on, and the
expected pass/fail PROFILE is the point (C-16):

  * EX-1 Parkinson, EX-5 Peter (LC-2 rendered as streams): the driving variable
    is recovered as a gated condition with the right direction — PASS expected;
  * EX-7 Goodhart (LC-3): with the intervention marked as a `do:` key the
    regime-dependence is found BY NAME; unmarked, the collapse is still located
    as a DATE. But no machinery here predicts the decoupling before any
    post-intervention data exists — that boundary is asserted as expected
    behavior, because it is exactly T-1's claim about observational systems;
  * EX-8 / the EX-5 hazard (C-18 negative control): data generated by noise +
    regression to the mean must NOT yield the mechanism claim. Declining is the
    pass.

A profile deviating from this pattern falsifies or refines the document's
thesis (C-16) — which is why it lives in the claims suite, not conformance.
"""

from __future__ import annotations

import json
import random

import pytest

from candor.periphery import curiosity as C

from . import exemplars as X
from . import worlds as W
from .test_claims import seed_for

pytestmark = pytest.mark.claims


def _admitted_guards(m, fid):
    out = []
    for r in m.index.query(
            "SELECT body_json FROM candidates WHERE kind='guard' "
            "AND status='admitted' ORDER BY event_seq"):
        body = json.loads(r["body_json"])
        if body.get("target_fact") == fid:
            out.append(body)
    return out


def _build(pred, stream, stmt_type="frequency"):
    m = W.fresh_store("candor-battery-", actors=["tool:probe"])
    stmt = {"pred": pred, "args": ["probe"]}
    fid = W.admit(m, pred, ["probe"], stmt_type=stmt_type)
    W.feed(m, stmt, stream)
    m.run_gate()
    return m, stmt, fid


# ── EX-1 Parkinson (LC-2): originate the deadline-dependence ────────────────

def test_ex1_parkinson_deadline_dependence_originated():
    rng = random.Random(seed_for("ex1"))
    m, stmt, fid = _build("task_done_in_window", X.parkinson(240, rng))
    guards = _admitted_guards(m, fid)
    assert guards, "the deadline-dependence must surface as a gated condition"
    g = guards[0]
    assert g["conditioning_key"] == "deadline", \
        f"wrong frame chosen: {g['conditioning_key']}"
    assert g["body"]["guards"][0]["value"] == "short", \
        "direction must match the planted mechanism (short deadline → done)"
    m.close()


# ── EX-5 Peter (LC-2): originate the ceiling condition ──────────────────────

def test_ex5_peter_ceiling_condition_originated():
    rng = random.Random(seed_for("ex5"))
    m, stmt, fid = _build("performs_well", X.peter(240, rng))
    guards = _admitted_guards(m, fid)
    assert guards and guards[0]["conditioning_key"] == "tier"
    assert guards[0]["body"]["guards"][0]["value"] == "below_ceiling"
    m.close()


# ── EX-7 Goodhart (LC-3): regime named when marked, dated when not ──────────

def test_ex7_goodhart_marked_regime_found_by_name():
    rng = random.Random(seed_for("ex7", "marked"))
    m, stmt, fid = _build(
        "metric_tracks_goal", X.goodhart(200, 100, 0.9, 0.25, rng, marked=True))
    guards = _admitted_guards(m, fid)
    assert guards and guards[0]["conditioning_key"] == "do:optimize_metric", \
        "with the intervention logged, the regime-dependence is found by name"
    assert guards[0]["body"]["guards"][0]["value"] == "no", \
        "the coupling holds exactly where the metric is NOT the target"
    # Δ13: and it is LABELED as regime dependence, not a mere condition —
    # EX-7's abduced rule ("the coupling was regime-dependent") verbatim
    assert guards[0].get("regime_dependent") is True
    assert "regime_mixed" in m.predict(stmt, budget=10_000).caveats
    m.close()


def test_ex7_goodhart_unmarked_collapse_is_located():
    rng = random.Random(seed_for("ex7", "unmarked"))
    cp = 100
    m, stmt, fid = _build(
        "metric_tracks_goal", X.goodhart(200, cp, 0.9, 0.25, rng, marked=False))
    sup = [json.loads(r["body_json"]) for r in m.index.query(
        "SELECT body_json FROM candidates WHERE kind='supersede_valid_time' "
        "AND status='admitted'")]
    sup = [s for s in sup if s.get("fact_id") == fid]
    assert sup, "an unmarked collapse must still be located as a date"
    assert abs(sup[0]["changepoint_index"] - cp) <= 5, \
        f"located {sup[0]['changepoint_index']}, planted {cp}"
    # and the self-lag frame must not have eaten the routing (Δ10 rule)
    assert not _admitted_guards(m, fid)
    m.close()


def test_ex7_no_pre_intervention_prediction():
    """The LC-3 boundary, executable (T-1, C-16): before ANY post-intervention
    observation exists, the substrate's prediction is the pre-regime rate — it
    has no machinery to anticipate what do(target the metric) will change,
    because that content is absent from observational data by definition
    (EX-7's P(G|M,observe) != P(G|do(target M))). This test documents the wall
    the axioms doc calls E->A: closing it needs intervention access (P-1
    territory), not a better statistic over these observations."""
    rng = random.Random(seed_for("ex7", "boundary"))
    pre_only = X.goodhart(100, 100, 0.9, 0.25, rng, marked=True)   # cp beyond n
    m, stmt, fid = _build("metric_tracks_goal", pre_only)
    p = m.predict(stmt, budget=10_000)
    assert p.p > 0.7, "with only tracking-regime data, prediction tracks it"
    m.close()


# ── EX-8 / EX-5 hazard (C-18): the artifact must be declined ────────────────

def test_ex8_regression_artifact_is_declined():
    rng = random.Random(seed_for("ex8"))
    m, stmt, fid = _build("estimates_own_skill", X.regression_artifact(300, 0.6, rng))
    guards = _admitted_guards(m, fid)
    assert guards == [], \
        f"minted a mechanism from regression to the mean: {guards}"
    row = m.index.one("SELECT dispersion_flag FROM facts WHERE id=?", (fid,))
    assert not row["dispersion_flag"], \
        "a homogeneous stream must carry no dispersion verdict"
    # the self-lag frame (Δ10) must stay quiet on iid data too
    d = m.distribution(stmt)
    assert d["residual"]["conditioning_key"] is None
    m.close()
